apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meu-app
  namespace: argocd
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  # Source: onde estão os manifestos
  source:
    repoURL:  https://github.com/robarros/lab-argo-rollout.git # ALTERE AQUI
    targetRevision: main  # ou master, ou a branch desejada
    path: base  # caminho para os manifestos base
    
  # Destination: onde será aplicado
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  
  # Sync Policy: como o ArgoCD deve sincronizar
  syncPolicy:
    automated:
      prune: true      # Remove recursos que não estão mais no Git
      selfHeal: false   # Corrige drift automaticamente
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true  # Cria o namespace se não existir
      - RespectIgnoreDifferences=true  # Respeita ignoreDifferences durante selfHeal
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
        
# ignoreDifferences para ignorar mudanças gerenciadas pelo Argo Rollouts
  ignoreDifferences:
    - group: argoproj.io
      kind: Rollout
      jsonPointers:
        - /spec/replicas

