apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meu-app
  namespace: argocd
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  # Definindo o projeto ArgoCD
  project: default

  # Setando um limite de histórico de revisões para evitar acúmulo
  revisionHistoryLimit: 3
  
  # Source: onde estão os manifestos
  source:
    repoURL:  https://github.com/robarros/lab-argo-rollout.git # ALTERE AQUI
    targetRevision: main  # ou master, ou a branch desejada
    path: base  # caminho para os manifestos base
    
  # Destination: onde será aplicado
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  
  # Sync Policy: como o ArgoCD deve sincronizar
  syncPolicy:
    automated:
      prune: true      # Remove recursos que não estão mais no Git
      selfHeal: true   # Corrige drift automaticamente
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
        
# ignoreDifferences para ignorar mudanças gerenciadas pelo Argo Rollouts
  # ignoreDifferences:
  #   - group: argoproj.io
  #     kind: Rollout
  #     jsonPointers:
  #       - /spec/replicas
  # ignoreDifferences:
  # - group: networking.istio.io
  #   kind: VirtualService
  #   jqPathExpressions:
  #     - .spec.http[].route[].weight
  #     - .status
  #     - .spec.hosts

